version: '3'

services:

  mongo-database:
    image: bitnami/mongodb:4.2
    restart: always
    environment:
      - MONGODB_USERNAME=mongouser
      - MONGODB_DATABASE=secret_santa
      - MONGODB_PASSWORD=${MONGO_PASS}
      - MONGODB_ROOT_PASSWORD=${MONGO_ROOT_PASS}
    volumes:
      - "mongo-data:/data/db"

  secret-santa-service:
    build: secret-santa-service
    depends_on:
      - mongo-database
    restart: always
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo-database
      - SPRING_DATA_MONGODB_USERNAME=mongouser
      - SPRING_DATA_MONGODB_DATABASE=secret_santa
      - SPRING_DATA_MONGODB_PASSWORD=${MONGO_PASS}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASS}
      - SPRING_MAIL_HOST=smtp.strato.de
      - SPRING_MAIL_PORT=465
      - SPRING_MAIL_USERNAME=secret-santa@mrtimeey.de
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLE=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_TRANSPORT_PROTOCOL=smtp
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
      
  secret-santa-ui:
    build: secret-santa-ui
    restart: always
    depends_on:
      - secret-santa-service
    ports:
      - 8085:80

volumes:
  mongo-data:
    driver: local
