server:
  error:
    include-stacktrace: never
  port: 8080

springdoc:
  api-docs:
    path: /api-docs/openapi
  swagger-ui:
    path: /api-docs/swagger-ui.html
    url: /api-docs/openapi
  show-actuator: true
