server:
  port: 8084

spring:
  data:
    mongodb:
      host: localhost
      username: mongouser
      password: ${MAIL_PASSWORD:123456}
      database: secret_santa
  mail:
    host: smtp.strato.de
    port: 465
    username: secret-santa@mrtimeey.de
    password: ${MAIL_PASSWORD:TBD}
    properties:
      "mail.smtp.ssl.enable": true
      "mail.smtp.auth": true
      "mail.transport.protocol": smtp
      "mail.smtp.starttls.enable": true
