spring:
  data:
    mongodb:
      host: localhost
      username: mongouser
      password: ${MONGODB_PASSWORD}
      database: secret_santa
  mail:
    host: smtp.strato.de
    port: 465
    username: no-reply@the-secret-santa.de
    password: ${MAIL_PASSWORD}
    properties:
      "mail.smtp.ssl.enable": true
      "mail.smtp.auth": true
      "mail.transport.protocol": smtp
      "mail.smtp.starttls.enable": true