name: main
on: [push]
jobs:
  build-and-test-frontend:
    runs-on: ubuntu-latest
    name: Build and test
    env:
        working-directory: ./secret-santa-ui
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        working-directory: ${{env.working-directory}}
      - run: npm t
        working-directory: ${{env.working-directory}}
